// Sensemaker Agent: produces a wave-level memory patch and an immediate insight.
// The insight is generated by the model (or fixture); the memory patch is built
// deterministically by the host from the answers and the insight.
// See .loom/design/adaptive-interview-system.md §3

import { z } from "zod";
import { generateStructured } from "@/lib/ai/client";
import { buildWavePatch, defaultInsightForWave } from "@/lib/ai/sensemaker/build-wave-patch";
import type { SensemakerWaveInput, SensemakerWaveOutput, ImmediateInsight } from "@/lib/working-memory/types";

const insightSchema = z
  .object({
    observation: z.string().min(1).max(120),
    interpretation: z.string().min(1).max(120),
    uncertainty: z.string().min(1).max(80),
    evidence_ids: z.array(z.string()).min(1).max(3),
    confidence: z.enum(["low", "medium", "high"]),
    kind: z.enum(["pattern", "tension", "constraint", "possibility"]),
    feedback_prompt: z.string().min(1).max(100),
  })
  .strict();

function makePrompt(input: SensemakerWaveInput): string {
  const answered = input.answers
    .filter((a) => !a.skipped)
    .map((a) => {
      const q = input.questions.find((qq) => qq.id === a.question_id);
      const value = Array.isArray(a.value) ? a.value.join("；") : a.value;
      return q ? `问题：${q.text}\n回答：${value}` : `问题：${a.question_id}\n回答：${value}`;
    })
    .join("\n\n");

  const memorySummary = input.memory.claims
    .filter((c) => c.status === "active")
    .slice(0, 3)
    .map((c) => `- ${c.text}`)
    .join("\n");

  const focus = input.focus_uncertainty_id
    ? input.memory.uncertainties.find((u) => u.id === input.focus_uncertainty_id)
    : undefined;

  return [
    `你是一名 Sensemaker Agent。你的单一职责是把本波回答转化为一个基于证据的即时洞察提案。`,
    ``,
    `本波焦点未知：${focus ? focus.question : "（首波模板，无单一焦点）"}`,
    ``,
    `用户回答：`,
    answered || "（本波全部跳过）",
    ``,
    `当前活跃的理解：`,
    memorySummary || "（还没有形成理解）",
    ``,
    `请输出一条 JSON 即时洞察。必须严格区分三栏：`,
    `- observation：用户告诉我的具体事实或场景，不加入解释，最多 80 字。`,
    `- interpretation：基于上述事实的暂定理解，使用条件式、试探性语言，不下结论，最多 100 字。`,
    `- uncertainty：一个可能推翻或大幅改变这个理解的未知，最多 50 字。`,
    ``,
    `evidence_ids 引用本波回答，1-3 个；输出 ["e1", "e2"] 这样的占位数组，宿主会替换为实际 id。`,
    `confidence：low / medium / high，仅用于内部流程，不展示。`,
    `kind：pattern / tension / constraint / possibility。`,
    `feedback_prompt：一句中性的邀请，让用户校准整条理解，不能问下一题。`,
    ``,
    `禁止：人格/临床标签、创伤推测、隐藏动机、自信百分比、"最佳""推荐""应该"、覆盖率的完成感语言。`,
  ].join("\n");
}

export async function runSensemakerWave(input: SensemakerWaveInput): Promise<SensemakerWaveOutput> {
  try {
    const generatedInsight = await generateStructured({
      purpose: "sensemaker_wave",
      session_id: input.session_id,
      wave_id: input.wave_id,
      prompt: makePrompt(input),
      schema: insightSchema,
      max_tokens: 1200,
      prompt_version: "sensemaker.wave.v1",
      fixture: () => Promise.resolve(defaultInsightForWave(input) as ImmediateInsight),
    });

    // The model's evidence_ids are placeholders; the host replaces them with real ids.
    const insight: ImmediateInsight = {
      ...generatedInsight,
      evidence_ids: [] as unknown as [string, ...string[]],
    };

    return buildWavePatch(input, insight);
  } catch (err) {
    // If the model fails, fall back to the deterministic patch.
    console.error("Sensemaker wave failed, using fallback:", err instanceof Error ? err.message : "unknown");
    return buildWavePatch(input, defaultInsightForWave(input));
  }
}
